### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by minus14** [fbeek/pimatic-maxcul#23]
Seems to be related to maxcul :

> error [pimatic]: A uncaught exception occured: TypeError: undefined is not a function
    at MaxDriver.handleIncommingMessage (/home/pi/pimatic-app/node_modules/pimatic-maxcul/max-driver.coffee:113:13)
    at CommunicationServiceLayer.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-maxcul/max-driver.coffee:40:10)
    at emitOne (events.js:96:13)
    at CommunicationServiceLayer.emit (events.js:188:7)
    at SerialPort.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-maxcul/communication-layer.coffee:74:14)
    at emitOne (events.js:96:13)
    at SerialPort.emit (events.js:188:7)
    at /home/pi/pimatic-app/node_modules/serialport/lib/parsers.js:24:17
    at Array.forEach (native)
    at Object.parser (/home/pi/pimatic-app/node_modules/serialport/lib/parsers.js:23:13)
    at SerialPort.<anonymous> (/home/pi/pimatic-app/node_modules/serialport/lib/serialport.js:147:14)
    at SerialPort._emitData (/home/pi/pimatic-app/node_modules/serialport/lib/serialport.js:350:18)
    at SerialPort.<anonymous> (/home/pi/pimatic-app/node_modules/serialport/lib/serialport.js:330:14)
    at SerialPort.<anonymous> (/home/pi/pimatic-app/node_modules/serialport/lib/serialport.js:343:7)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by fbeek** [comment]
I could not comprehend the bug but a added an error handler to the function so that there is a log message an pimatic should not crash.
